### ISSUE TITLE
What is order in the algorithm?

### ISSUE THREAD

**Issue by TaoRuan-Campus** [YangLiangwei/Influential-nodes-identification-in-complex-networks-via-information-entropy#1]
Hello. I am wondering what the argument "order" means in your EnRenewRank algorithm and how we should decide the value for it?

**Comment by Victordmz** [comment]
I think the order parameter in the algorithm is the _l_ parameter in the article, i.e. the extent to which information entropy attenuation has to find place, in a range of length _l_ (= `order`) from selected node _v_. This is to cope with the rich-club phenomenon. It is a good idea to check the rich-club coefficient trend for the graph in question and select `order` accordingly. In the article a value of 2 is proposed.

So the larger `order`, the larger the attenuation range from _v_.

**Comment by YangLiangwei** [comment]
@TaoRuan-Campus, the explanation of Victordmz is correct. In practice, we treat it as a hyperparameter to tune. From experiments, different values of it fit different dataset.
